### PR TITLE
Fix Floodligut WebGUI switchDetail.html throwing error on OpenFlow 1.4

### PR DESCRIPTION
**Pull request by QingWang0909**
This is for Floodlight Issue #778 ...

### CODE REVIEW

**Comment by QingWang0909** [comment]
@geddings could you please take a look on this quick fix for Floodlight issue #778 (https://github.com/floodlight/floodlight/issues/778)? Basically the problem is here (https://github.com/floodlight/floodlight-webui/blob/master/pages/switchDetail.html#L579) -- in OpenFlow 1.4 in port reply message they moved the "port collisions" into "properties" -- to access, now it is "port.0.properties.collisions".  Thanks!

**Comment by geddings-bsn** [comment]
LGTM

**Comment by qingwang-bsn** [comment]
@geddings-bsn Thanks for reviewing it!  Could you please merge it? I don't think I have permission on this repository.

**Comment by WULINPIN** [comment]
thank you,i vim switchDetail.html ，remove port.0.properties.collisions, and rebuild by ant,everything is good, it works. error page not

**Pull request merged**
